name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  notify:
    name: Push Notification
    runs-on: ubuntu-latest

    steps:
      - name: Echo pushed
        run: echo "🚀 pushed"
